[package]
name = "odd-engine"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
json = "0.12.4"
once_cell = "1.15.0"
rayon = "1.5.3"
regex = "1.6.0"

[dev-dependencies]
fastrand = "1.8.0"
